name: Release & Publish
on:
  workflow_dispatch:
  push:
    branches: main

permissions: {}
jobs:
  release:
    name: Release
    permissions:
      contents: write # to create release (changesets/action)
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH keys
        uses: shimataro/ssh-key-action@v2.7.0
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: github.com

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup node cache
        id: node-cache
        uses: actions/cache@v4.0.2
        with:
          path: '**/node_modules'
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-

      - name: Setup turbo cache
        uses: actions/cache@v4.0.2
        with:
          path: '.turbo'
          key: turbo-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.ref_name }}-
            turbo-main-

      - name: Install deps
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Setup git
        run: |
          git config user.name "$GIT_USER_NAME"
          git config user.email "$GIT_USER_EMAIL"
        env:
          GIT_USER_NAME: ${{ vars.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL }}

      - name: Setup npm auth
        run: echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Run Release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
